name: CI
on: push
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.2
      - name: Install Goimports
        run: GO111MODULE=on go get golang.org/x/tools/cmd/goimports
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.8
      - name: Check editorconfig formatting
        uses: editorconfig-checker/action-editorconfig-checker@main
      - name: Check formatting
        run: make fmt-check
      - name: Run tests
        run: make check

